server:
  port: 8020 

spring:
  application:   #定义服务名称
    name: consume-user
eureka:
  client:
    register-with-eureka: true    #将自己的信息注册到eureka中
    service-url:
      #链接注册中心集群
       defaultZone: http://localhost:7000/eureka
  instance: 
    instance-id: consume-user-8020                #定义微服务的名称 
    prefer-ip-address: true                        #是否显示IP和端口
    
feign:
  hystrix:
    enabled: true                 #启动熔断器机制 !!!!!!!!!!!!!

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000  #设定熔断器超时时间
            
    